import melonManchegoImg from '@/imports/image-3.png'

export const FRUTAS = [
  {
    name: 'Melón Manchego',
    desc: 'El auténtico melón de La Mancha. Dulce, aromático y de pulpa blanca cremosa.',
    tag: 'Temporada',
    origin: 'La Mancha',
    img: melonManchegoImg,
    alt: 'Melón manchego fresco',
  },
  {
    name: 'Sandía',
    desc: 'Grande, roja y refrescante. De los campos de Tarragona directamente a tu mesa.',
    tag: 'Temporada',
    origin: 'Tarragona',
    img: 'https://images.unsplash.com/photo-1471745518196-ed32997e769c?w=600&h=600&fit=crop&auto=format',
    alt: 'Sandía fresca cortada',
  },
  {
    name: 'Melocotón',
    desc: 'Piel aterciopelada, pulpa jugosa y aroma inconfundible. Temporada al máximo.',
    tag: 'Fresco',
    origin: 'Lleida',
    img: 'https://images.unsplash.com/photo-1634213704824-9c9782559a08?w=600&h=600&fit=crop&auto=format',
    alt: 'Melocotón fresco',
  },
  {
    name: 'Paraguayos',
    desc: 'Planos, dulcísimos y fáciles de comer. Un clásico del verano mediterráneo.',
    tag: 'Verano',
    origin: 'Lleida',
    img: 'https://images.unsplash.com/photo-1642372849578-c2142f64add6?w=600&h=600&fit=crop&auto=format',
    alt: 'Paraguayos frescos',
  },
  {
    name: 'Plátano Canario',
    desc: 'De las Islas. Más pequeño, más dulce, mucho más sabor que el importado.',
    tag: 'Canarias',
    origin: 'Canarias',
    img: 'https://images.unsplash.com/photo-1571771894821-ce9b6c11b08e?w=600&h=600&fit=crop&auto=format',
    alt: 'Plátanos canarios',
  },
  {
    name: 'Banana Tropical',
    desc: 'Importación directa. Maduramos en tienda para garantizar el punto perfecto.',
    tag: 'Tropical',
    origin: 'Sudamérica',
    img: 'https://images.unsplash.com/photo-1603833665858-e61d17a86224?w=600&h=600&fit=crop&auto=format',
    alt: 'Banana tropical fresca',
  },
  {
    name: 'Mango',
    desc: 'Seleccionado en su punto óptimo. Dulce, carnoso y lleno de sabor tropical.',
    tag: 'Tropical',
    origin: 'Sudamérica',
    img: 'https://images.unsplash.com/photo-1601493700631-2b16ec4b4716?w=600&h=600&fit=crop&auto=format',
    alt: 'Mangos tropicales',
  },
  {
    name: 'Maracuyá',
    desc: 'El sabor de Latinoamérica. Ácido, aromático e irresistible para batidos.',
    tag: 'Latino',
    origin: 'Sudamérica',
    img: 'https://images.unsplash.com/photo-1604495772376-9657f0035eb5?w=600&h=600&fit=crop&auto=format',
    alt: 'Maracuyá fruta de la pasión',
  },
  {
    name: 'Ciruelas',
    desc: 'Jugosas, aromáticas y con el punto justo entre dulzor y acidez.',
    tag: 'Fresco hoy',
    origin: 'Lleida',
    img: 'https://images.unsplash.com/photo-1564750497011-ead0ce4b9448?w=600&h=600&fit=crop&auto=format',
    alt: 'Ciruelas moradas frescas',
  },
  {
    name: 'Limones',
    desc: 'Cítricos, fragantes y llenos de zumo. Imprescindibles en cualquier cocina.',
    tag: 'Fresco hoy',
    origin: 'Murcia',
    img: 'https://images.unsplash.com/photo-1590502593747-42a996133562?w=600&h=600&fit=crop&auto=format',
    alt: 'Limones amarillos frescos',
  },
  {
    name: 'Uvas',
    desc: 'Racimos frescos de grano firme, jugoso y naturalmente dulce.',
    tag: 'Fresco hoy',
    origin: 'Alicante',
    img: 'https://images.unsplash.com/photo-1698305819486-ecca56daaba3?w=600&h=600&fit=crop&auto=format',
    alt: 'Racimo de uvas frescas',
  },
  {
    name: 'Guayaba',
    desc: 'Aromática, suave y tropical. Rica en sabor y perfecta para tomar al natural.',
    tag: 'Fresco hoy',
    origin: 'Colombia',
    img: 'https://images.unsplash.com/photo-1693399991519-bef70bed19a2?w=600&h=600&fit=crop&auto=format',
    alt: 'Guayabas verdes y maduras',
  },
]

export const VERDURAS = [
  {
    name: 'Calabacín del Campo',
    desc: 'De proximidad, recogido antes de abrir. Tierno, sin amargor.',
    tag: 'Proximidad',
    origin: 'Lleida',
    img: 'https://images.unsplash.com/photo-1449300079323-02e209d9d3a6?w=600&h=600&fit=crop&auto=format',
    alt: 'Calabacines frescos',
  },
  {
    name: 'Pepinos del Campo',
    desc: 'Cultivados con mimo, crujientes y frescos. Kilómetro cero.',
    tag: 'Proximidad',
    origin: 'Lleida',
    img: 'https://images.unsplash.com/photo-1589621316382-008455b857cd?w=600&h=600&fit=crop&auto=format',
    alt: 'Pepinos frescos',
  },
  {
    name: 'Pimiento Verde',
    desc: 'Para freír, asar o en ensalada. Directo del agricultor, sin intermediarios.',
    tag: 'Campo',
    origin: 'Lleida',
    img: 'https://images.unsplash.com/photo-1585159079680-8dec029b76ed?w=600&h=600&fit=crop&auto=format',
    alt: 'Pimiento verde fresco',
  },
  {
    name: 'Pimiento Rojo',
    desc: 'Maduro al sol, dulce y carnoso. Ideal para asar o comer en crudo.',
    tag: 'Campo',
    origin: 'Lleida',
    img: 'https://images.unsplash.com/photo-1608737637507-9aaeb9f4bf30?w=600&h=600&fit=crop&auto=format',
    alt: 'Pimiento rojo fresco',
  },
  {
    name: 'Pimiento Italiano',
    desc: 'Largo, dulce y jugoso. El favorito para hacer a la plancha.',
    tag: 'Campo',
    origin: 'Lleida',
    img: 'https://images.unsplash.com/photo-1525607551316-4a8e16d1f9ba?w=600&h=600&fit=crop&auto=format',
    alt: 'Pimiento italiano fresco',
  },
  {
    name: 'Tomate para Gazpacho',
    desc: 'Varietales maduros seleccionados para tu gazpacho casero perfecto.',
    tag: 'Del campo',
    origin: 'Lleida',
    img: 'https://images.unsplash.com/photo-1618807543816-96d6df00de29?w=600&h=600&fit=crop&auto=format',
    alt: 'Tomates para gazpacho',
  },
  {
    name: 'Tomates del Campo',
    desc: 'Tomates de verdad, con sabor a verano. Directos del campo a la tienda.',
    tag: 'Del campo',
    origin: 'Lleida',
    img: 'https://images.unsplash.com/photo-1582284540020-8acbe03f4924?w=600&h=600&fit=crop&auto=format',
    alt: 'Tomates frescos del campo',
  },
  {
    name: 'Aceitunas a Granel',
    desc: 'Verdes, negras y variadas. A granel, aliñadas con hierbas y especias de la huerta.',
    tag: 'A granel',
    origin: 'Lleida',
    img: 'https://images.unsplash.com/photo-1634657443172-efbae44fd04b?w=600&h=600&fit=crop&auto=format',
    alt: 'Aceitunas a granel verdes y negras',
  },
  {
    name: 'Col',
    desc: 'Hojas firmes y crujientes, ideal para guisos, ensaladas y platos de cuchara.',
    tag: 'Fresco hoy',
    origin: 'Lleida',
    img: 'https://images.unsplash.com/photo-1611105637889-3afd7295bdbf?w=600&h=600&fit=crop&auto=format',
    alt: 'Col verde fresca',
  },
  {
    name: 'Calabaza',
    desc: 'Dulce, cremosa y versátil. Perfecta para asar, preparar cremas o cocinar al horno.',
    tag: 'Fresco hoy',
    origin: 'Valencia',
    img: 'https://images.unsplash.com/photo-1509622905150-fa66d3906e09?w=600&h=600&fit=crop&auto=format',
    alt: 'Calabazas frescas de distintos colores',
  },
  {
    name: 'Berenjenas',
    desc: 'Tiernas, brillantes y carnosas. Ideales para asar, rellenar o cocinar a la plancha.',
    tag: 'Fresco hoy',
    origin: 'Almería',
    img: 'https://images.unsplash.com/photo-1528826007177-f38517ce9a8a?w=600&h=600&fit=crop&auto=format',
    alt: 'Berenjena morada fresca',
  },
  {
    name: 'Yuca',
    desc: 'Raíz firme y sabrosa, perfecta para hervir, freír o acompañar tus platos.',
    tag: 'Fresco hoy',
    origin: 'Costa Rica',
    img: 'https://images.unsplash.com/photo-1757283961570-682154747d9c?w=600&h=600&fit=crop&auto=format',
    alt: 'Raíces de yuca frescas',
  },
]
