import melonManchegoImg from '@/imports/image-3.png'

export const FRUTAS = [
  {
    name: 'Melón Manchego',
    desc: 'El auténtico melón de La Mancha. Dulce, aromático y de pulpa blanca cremosa.',
    tag: 'Temporada',
    origin: 'La Mancha',
    img: melonManchegoImg,
    alt: 'Melón manchego fresco',
  },
  {
    name: 'Sandía',
    desc: 'Grande, roja y refrescante. De los campos de Tarragona directamente a tu mesa.',
    tag: 'Temporada',
    origin: 'Tarragona',
    img: 'https://images.unsplash.com/photo-1471745518196-ed32997e769c?w=600&h=600&fit=crop&auto=format',
    alt: 'Sandía fresca cortada',
  },
  {
    name: 'Melocotón',
    desc: 'Piel aterciopelada, pulpa jugosa y aroma inconfundible. Temporada al máximo.',
    tag: 'Fresco',
    origin: 'Lleida',
    img: 'https://images.unsplash.com/photo-1634213704824-9c9782559a08?w=600&h=600&fit=crop&auto=format',
    alt: 'Melocotón fresco',
  },
  {
    name: 'Paraguayos',
    desc: 'Planos, dulcísimos y fáciles de comer. Un clásico del verano mediterráneo.',
    tag: 'Verano',
    origin: 'Lleida',
    img: 'https://images.unsplash.com/photo-1642372849578-c2142f64add6?w=600&h=600&fit=crop&auto=format',
    alt: 'Paraguayos frescos',
  },
  {
    name: 'Plátano Canario',
    desc: 'De las Islas. Más pequeño, más dulce, mucho más sabor que el importado.',
    tag: 'Canarias',
    origin: 'Canarias',
    img: 'https://images.unsplash.com/photo-1571771894821-ce9b6c11b08e?w=600&h=600&fit=crop&auto=format',
    alt: 'Plátanos canarios',
  },
  {
    name: 'Banana Tropical',
    desc: 'Importación directa. Maduramos en tienda para garantizar el punto perfecto.',
    tag: 'Tropical',
    origin: 'Sudamérica',
    img: 'https://images.unsplash.com/photo-1603833665858-e61d17a86224?w=600&h=600&fit=crop&auto=format',
    alt: 'Banana tropical fresca',
  },
  {
    name: 'Mango',
    desc: 'Seleccionado en su punto óptimo. Dulce, carnoso y lleno de sabor tropical.',
    tag: 'Tropical',
    origin: 'Sudamérica',
    img: 'https://images.unsplash.com/photo-1601493700631-2b16ec4b4716?w=600&h=600&fit=crop&auto=format',
    alt: 'Mangos tropicales',
  },
  {
    name: 'Maracuyá',
    desc: 'El sabor de Latinoamérica. Ácido, aromático e irresistible para batidos.',
    tag: 'Latino',
    origin: 'Sudamérica',
    img: 'https://images.unsplash.com/photo-1604495772376-9657f0035eb5?w=600&h=600&fit=crop&auto=format',
    alt: 'Maracuyá fruta de la pasión',
  },
]

export const VERDURAS = [
  {
    name: 'Calabacín del Campo',
    desc: 'De proximidad, recogido antes de abrir. Tierno, sin amargor.',
    tag: 'Proximidad',
    origin: 'Lleida',
    img: 'https://images.unsplash.com/photo-1449300079323-02e209d9d3a6?w=600&h=600&fit=crop&auto=format',
    alt: 'Calabacines frescos',
  },
  {
    name: 'Pepinos del Campo',
    desc: 'Cultivados con mimo, crujientes y frescos. Kilómetro cero.',
    tag: 'Proximidad',
    origin: 'Lleida',
    img: 'https://images.unsplash.com/photo-1589621316382-008455b857cd?w=600&h=600&fit=crop&auto=format',
    alt: 'Pepinos frescos',
  },
  {
    name: 'Pimiento Verde',
    desc: 'Para freír, asar o en ensalada. Directo del agricultor, sin intermediarios.',
    tag: 'Campo',
    origin: 'Lleida',
    img: 'https://images.unsplash.com/photo-1585159079680-8dec029b76ed?w=600&h=600&fit=crop&auto=format',
    alt: 'Pimiento verde fresco',
  },
  {
    name: 'Pimiento Rojo',
    desc: 'Maduro al sol, dulce y carnoso. Ideal para asar o comer en crudo.',
    tag: 'Campo',
    origin: 'Lleida',
    img: 'https://images.unsplash.com/photo-1608737637507-9aaeb9f4bf30?w=600&h=600&fit=crop&auto=format',
    alt: 'Pimiento rojo fresco',
  },
  {
    name: 'Pimiento Italiano',
    desc: 'Largo, dulce y jugoso. El favorito para hacer a la plancha.',
    tag: 'Campo',
    origin: 'Lleida',
    img: 'https://images.unsplash.com/photo-1525607551316-4a8e16d1f9ba?w=600&h=600&fit=crop&auto=format',
    alt: 'Pimiento italiano fresco',
  },
  {
    name: 'Tomate para Gazpacho',
    desc: 'Varietales maduros seleccionados para tu gazpacho casero perfecto.',
    tag: 'Del campo',
    origin: 'Lleida',
    img: 'https://images.unsplash.com/photo-1618807543816-96d6df00de29?w=600&h=600&fit=crop&auto=format',
    alt: 'Tomates para gazpacho',
  },
  {
    name: 'Tomates del Campo',
    desc: 'Tomates de verdad, con sabor a verano. Directos del campo a la tienda.',
    tag: 'Del campo',
    origin: 'Lleida',
    img: 'https://images.unsplash.com/photo-1582284540020-8acbe03f4924?w=600&h=600&fit=crop&auto=format',
    alt: 'Tomates frescos del campo',
  },
  {
    name: 'Aceitunas a Granel',
    desc: 'Verdes, negras y variadas. A granel, aliñadas con hierbas y especias de la huerta.',
    tag: 'A granel',
    origin: 'Lleida',
    img: 'https://images.unsplash.com/photo-1634657443172-efbae44fd04b?w=600&h=600&fit=crop&auto=format',
    alt: 'Aceitunas a granel verdes y negras',
  },
]

export const BATIDOS = [
  {
    name: 'Batido de Mango',
    desc: 'Mango tropical triturado al momento. Sin azúcar añadido, pura fruta.',
    tag: 'Natural',
    origin: 'Sudamérica',
    img: 'https://images.unsplash.com/photo-1622597467821-df79dcb4f94d?w=600&h=600&fit=crop&auto=format',
    alt: 'Batido natural de mango',
  },
  {
    name: 'Batido Tropical',
    desc: 'Piña, mango y maracuyá. Un viaje a Latinoamérica en cada sorbo.',
    tag: 'Latino',
    origin: 'Sudamérica',
    img: 'https://images.unsplash.com/photo-1583577612013-4fecf7bf8f13?w=600&h=600&fit=crop&auto=format',
    alt: 'Batidos tropicales coloridos',
  },
  {
    name: 'Batido de Fresas',
    desc: 'Fresas naturales con leche o agua de coco. Pura vitamina en vaso.',
    tag: 'Natural',
    origin: 'Lleida',
    img: 'https://images.unsplash.com/photo-1570696516188-ade861b84a49?w=600&h=600&fit=crop&auto=format',
    alt: 'Batido natural de fresas',
  },
  {
    name: 'Batido de Guanábana',
    desc: 'Un clásico latino cremoso y refrescante. Sabor único e inconfundible.',
    tag: 'Latino',
    origin: 'Sudamérica',
    img: 'https://images.unsplash.com/photo-1603569283847-aa295f0d016a?w=600&h=600&fit=crop&auto=format',
    alt: 'Batido de frutas variadas',
  },
]
